version: 2
jobs:
  frontend-unit-test:
    docker:
      - image: circleci/node:10.12.0
    steps:
      - checkout
      - run: echo "A first Hello"
workflows:
  version: 2
    frontend:
      jobs:
        - frontend-unit-test