version: 2
jobs:
  frontend-unit-test:
    docker:
      - image: circleci/node:10.12.0
    steps:
      - checkout
      - run:
        name: Lint Frontend
        shell: /bin/bash
        working_directory: ~/Web-FrontEnd/client
        command: npm run lint
        no_output_timeout: 5m
      - run:
        name: Frontend Unit Test
        shell: /bin/bash
        working_directory: ~/Web-FrontEnd/client
        command: npm run test
        no_output_timeout: 5m
workflows:
  version: 2
  frontend:
    jobs:
      - frontend-unit-test