version: 2
jobs:
  frontend-unit-test:
    docker:
      - image: circleci/node:10.12.0
    steps:
      - checkout
      - run: npm -v
workflows:
  version: 2
  frontend:
    jobs:
      - frontend-unit-test